In [2]:
import pandas as pd

df=pd.read_csv('diabetes.csv')

df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [9]:
groupBy= df.groupby('Age')['BMI'].mean()

groupBy

Age
21    27.817460
22    29.509722
23    31.502632
24    32.569565
25    31.943750
26    34.915152
27    31.950000
28    33.642857
29    33.541379
30    30.033333
31    34.016667
32    32.318750
33    32.335294
34    31.164286
35    33.780000
36    31.718750
37    32.078947
38    35.568750
39    31.983333
40    33.538462
41    35.259091
42    34.983333
43    36.892308
44    34.162500
45    34.960000
46    34.523077
47    34.566667
48    29.980000
49    32.020000
50    31.225000
51    33.975000
52    33.475000
53    30.500000
54    30.800000
55    27.025000
56    31.700000
57    29.700000
58    32.428571
59    26.966667
60    28.740000
61    30.000000
62    28.950000
63    30.775000
64    25.000000
65    31.600000
66    30.375000
67    28.766667
68    35.600000
69    13.400000
70    32.500000
72    19.600000
81    25.900000
Name: BMI, dtype: float64